name: cuefinger # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Remote-control Universal Audio's Console # 79 char long summary
description: |
  Cuefinger gives you the possibility to remote control Universal Audio's Console Application via Network (TCP).
license: GPL-3.0
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
    
architectures:
  - build-on: amd64  

icon: cuefinger.png

layout:
  $SNAP/usr/local/data:
    bind: $SNAP/usr/local/share

lint:
  ignore:
    - library:
        - usr/lib/x86_64-linux-gnu/libpulse-simple.so.0.1.1

apps:
  cuefinger:
    command: usr/local/bin/cuefinger
    desktop: usr/local/share/cuefinger.desktop
    extensions: [gnome]
    plugs:
      - network
    
parts:
  cuefinger:
    plugin: autotools
    source: https://github.com/franqulator/cuefinger
    source-type: git
    build-packages:
      - g++
      - make
      - libsdl2-dev
      - libsdl2-ttf-dev
    stage-packages:
      - libpulse0
      - libsdl2-2.0-0
      - libsdl2-ttf-2.0-0

